---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: /blog/:title ## disables post output
timezone: null
lsi: false
markdown: kramdown


### content configuration ###
title:       "Sarah M Brown, PhD"
name:        "Sarah M Brown"
keywords:    "machine learning, research, stem diversity"
description: "Sarah M Brown, PhD "
source_link: "https://github.com/brownsarahm/brownsarahm.github.io"
favicon:     "img/favicon.ico"
touch_icon:  "img/apple-touch-icon.png"
##google_analytics_key: UA-49607422-1 ## put YOUR key here to enable tracking! (blank to disable)

social:
  github: brownsarahm
  twitter: brownsarahm
  linkedin: smariebrown

### template colors, used site-wide via css ###
colors:
  black: '#2A312E'
  white: '#FBFBFB'
#  white:     '#D9E2E5'
  gray:      '#2A312E'
  magenta:   '#92374D'
  purple: '#462138'
  blue: '#8EB1C7'
  teal: '#556F7A'
  # unused

  green:     '#9bcf2f'
##  purple:    '#c869bf'
  orange:    '#fab125'

include:
  - _pages
  - files


kramdown:
  auto_ids:  false

collections:
  bio:
  academic:
    output: true
    permalink: /:name/
    display: home
    menuloc: ''
  research:
    output: true
    display: research
    menuloc: research
    permalink: /:collection/:title
  service:
    output: true
    display: service
    menuloc: service
    permalink: /:collection/:title
  speaking:
    output: true
    display: speaking
    menuloc: speaking
    permalink: /:collection/:title
  teaching:
    output: true
    display: teaching
    menuloc: teaching
    permalink: /:collection/:year/:title
  blog:
    output: true
    permalink: /:collection/:namp
    display: blog
    menuloc: blog
  category:
    output: true
    permalink: /:collection/:name/
